.gitignore, Makefile, include/dolphin/mtx/mtxtypes.h, include/dolphin/types.h, include/global.h
* Adds typedefs for u8, etc.
* Adds additional typedefs for the geometry structs, Vector, Matrix3x4, and 4x4
* Adds .vscode directory to .gitignore
=> Initial types includes, update .gitignore

README.md
I ran into some issues with building the dol and figured some extra clarification in the README couldn't hurt.
=> Update README with required tools for building

asm/pobj.s, obj_files.mk, src/sysdolphin/pobj.c, src/sysdolphin/pobj.h
* Brings in the header file with some struct work that I'd previously done
* Matches HSD_PObjGetFlags since it's a simple function
=> Bring past work on PObj over and match a basic function

src/sysdolphin/id.c
Matched _HSD_IDForgetMemory and HSD_IDGetDataFromTable
=> Match two ID.c functions

Makefile, tools/elf2dol.c
Work done by the TP Decomp crew
=> Removes the objcopy hack

asm/MSL/abort_exit.s, asm/sdata2.s
Removes incbins in abort_exit and sdata2
=> Incbin cleanup

asm/data.s
=> Work through Character Data pointers

src/melee/lb/lbcommand.c, src/melee/lb/lbcommand.h
Created "Command_N_Struct" structs that could be used a union on offset 0x8, since clearly not everything treats it the same for matching to occur.
=> Remaining lbcommand matches

Makefile
=> lbtime makefile fix

Makefile, tools/calcprogress.py
=> output calcprogress to console if map output enabled

include/cstring.h, include/mem_funcs.h, include/stddef.h, obj_files.mk, src/MSL/cstring.c
Not sure what to name func_8032388C (assuming we only want an official symbol)
=> Decompiled `cstring.s`

src/sysdolphin/baselib/tobj.c, src/sysdolphin/baselib/tobj.h
Non-matching presently due to jump table. Need to address it.
=> Matched TObjUpdateFunc

Makefile, asm/sysdolphin/baselib/dobj.s, src/sysdolphin/baselib/class.h, src/sysdolphin/baselib/dobj.c
Removed some of the inline asm. Had to reintroduce inline asm for a function, because Frank either breaks one or the other and I chose the smaller function to be the broken one.
=> Work on cleaning up DObj

src/melee/pl/player.c
lots of clean up in player, remove ifdefs, and remove a bunch of decomp links, rename labels, etc
=> lots of clean up in player, remove ifdefs, and remove a bunch of decomp links, rename labels, etc

src/melee/ft/fighter.h
=> Fix bad merge of fighter.h

asm/melee/gr/grfourside.s, asm/melee/gr/grgreatbay.s
Also move some grgreatbay data out of grfourside
=> Translate ascii strings in grfourside/grgreatbay

src/melee/ft/chara/ftmario.c
Mario progress and fighter special attributes union need merge conflict
=> Fix conflicts

tools/frank.py
Pulls changes from https://github.com/projectPiki/pikmin/commit/4510b5f8a4f480738729da44e26235cba28f5979
=> frank.py: Pull latest changes

.github/workflows/build.yml, Makefile
Successful run: https://github.com/r-burns/doldecomp-melee/actions/runs/2145976860
=> ci: Also build non-matching dol

src/sysdolphin/baselib/list.c, src/sysdolphin/baselib/memory.c
* Remove extraneous inline function
* Simplify asserts with assert_line macro
=> HSD list, memory: minor cleanups

.github/workflows/build.yml, tools/mwld_patch.py, tools/mwld_postpatch.sha1, tools/mwld_prepatch.sha1
Not sure if this will work, but worth trying to get rid of the spurious wine failures.
=> Change github actions from wine to wibo

Makefile
@CelestialAmber lmk if this still works for you
=> Use shasum command on macOS, sha1sum otherwise

obj_files.mk
Better for git, vim, readability, etc.
=> Add line breaks to `obj_files.mk`

src/melee/ft/ftcommon.c
Fixes shiftability issue in ftcommon (https://github.com/doldecomp/melee/issues/465)
=> Fix match for func_80080174

asm/sysdolphin/baselib/fobj.s
=> Fix hardcoded addresses in `fobj.s`

build.sh
Outputs to `build.log`. Use `tail -f build.log` to watch in a shell.
=> Support logging (`-l`) in `build.sh`

CONTRIBUTING.md
=> Codify literal stylization in `CONTRIBUTING.md`

include/sysdolphin/baselib/jobj.h, src/melee/gr/grlib.c, src/melee/gr/ground.c, src/melee/it/item.c, src/melee/lb/lbunknown_001.c, src/sysdolphin/baselib/jobj.c
Closes https://github.com/doldecomp/melee/issues/536
=> JObj cleanup

src/dolphin/gx/GXBump.c, src/dolphin/gx/GXFrameBuf.c, src/dolphin/gx/GXTev.c, src/dolphin/gx/GXTexture.c, src/dolphin/gx/GXTransform.c, src/dolphin/gx/__GX_unknown_001.h
Refactor to prefer INSERT_FIELD macro
=> More gx matches & cleanup

src/sysdolphin/baselib/lobj.c, src/sysdolphin/baselib/lobj.h
Match some inline asm functions
Reduce code duplication using inlines
=> Improve lobj matches

asm/melee/ft/ftparts.s, src/melee/ft/fighter.c, src/melee/ft/fighter.h
Move all fighter HSD_ObjAllocData structs to fighter.c to remove fakematchy pointer arithmetic in Fighter_800679B0
=> Fix fighter.c .bss section

include/sysdolphin/baselib/gobj.h, src/melee/ft/fighter.c, src/melee/ft/fighter.h
Yoinked from https://github.com/doldecomp/melee/pull/614
=>  Fix GObjEvent function signatures in fighter.c

src/melee/ft/chara/ftLuigi/ftLuigi_SpecialS.c, src/melee/it/item.c, src/melee/it/types.h
Forgot to press the button on https://github.com/doldecomp/melee/pull/671#discussion_r1068968097.
=> Rename `Item` callbacks

src/dolphin/os/OSCache.h, src/dolphin/os/OSInit.h, src/dolphin/os/init/__ppc_eabi_init.c, src/dolphin/os/init/__start.c, src/dolphin/os/init/__start.h
As shown by other games' debug maps
=> Move __ppc_eabi_init function to correct TU

src/melee/ft/chara/ftNess/ftNess_SpecialHi.c
Depends on #699. Resolves #684.
```yml
Co-authored-by: VetriTheRetri <74500716+VetriTheRetri@users.noreply.github.com>
```
=> Re-match `ftNess_CheckSpecialHiHold`

.github/workflows/publish.yml, tools/ctx_template.html, tools/m2ctx/m2ctx.py
Looks like [this](https://ribbanya.github.io/melee/ctx.html).
=> Deploy `ctx.html` whenever `master` is updated

.github/workflows/editorconfig.yml
Applies https://github.com/NixOS/nixpkgs/commit/31ce09b37790915618e839ed6a728f7b40157fdc.
=> Fix editorconfig workflow

.github/workflows/editorconfig.yml
Works on this [run](https://github.com/ribbanya/melee/actions/runs/4301051155).
=> Use `github.ref` instead of `github.head_ref` [skip editorconfig]

.github/workflows/publish-packages.yml
Scheduled builds weren't being pushed.
=> Fix cron jobs not pushing packages

.github/workflows/build-melee.yml, .github/workflows/publish-packages.yml, .github/workflows/publish-pages.yml
I noticed @DRGN-DRC's [build was failing](https://github.com/DRGN-DRC/melee/actions/runs/4449315107/jobs/7813331863#step:5:1070) so this should fix it.
=> Convert package names to lowercase

src/melee/ft/code_8007C114.c, src/melee/ft/ft_unknown_006.h
=> Match `func_8007C114`

asm/melee/ft/chara/ftCaptain/ftCa_SpecialHi.s, obj_files.mk, src/melee/ft/chara/ftCaptain/ftCa_SpecialLw.c, src/melee/ft/chara/ftCaptain/ftCa_SpecialLw.h, src/melee/ft/chara/ftCaptain/types.h, src/melee/ft/chara/ftCommon/ftCo_Init.h, tools/convert_data.py, tools/report_score.py
-|-|-|-
`ftCa_SpecialHi_800E3EAC`|`874`|`71600`|`98.78%`
`ftCa_SpecialHi_800E400C`|`874`|`62800`|`98.61%`
`ftCa_SpecialLw_Enter`|`874`|`61500`|`98.58%`
`ftCa_SpecialAirLw_Enter`|`874`|`57700`|`98.49%`
`ftCa_SpecialLw_Anim`|`874`|`54400`|`98.39%`
`ftCa_SpecialAirLwEnd_Anim`|`684`|`41800`|`98.36%`
`ftCa_SpecialAirLwEndAir_Anim`|`684`|`40300`|`98.30%`
`ftCa_SpecialLwEnd_Anim`|`809`|`47700`|`98.30%`
`ftCa_SpecialLwEndAir_Anim`|`809`|`46200`|`98.25%`
`ftCa_SpecialHiThrow1_Anim`|`684`|`38800`|`98.24%`
`ftCa_SpecialAirLw_Anim`|`809`|`44700`|`98.19%`
`ftCa_SpecialLw_Phys`|`684`|`37300`|`98.17%`
`ftCa_SpecialLwEnd_Phys`|`684`|`33600`|`97.96%`
`ftCa_SpecialLwEndAir_Phys`|`684`|`28800`|`97.62%`
`ftCa_SpecialAirLw_Phys`|`684`|`25400`|`97.31%` …
=> Partially match all of `ftCa_SpecialLw`

docs/glossary.md, obj_files.mk, src/melee/ft/chara/ftCaptain/ftCa_SpecialHi.c, src/melee/ft/chara/ftCaptain/ftCa_SpecialHi.h, src/melee/ft/chara/ftCaptain/types.h, src/melee/ft/chara/ftDonkey/ftDk_Init.c, src/melee/ft/chara/ftFox/ftFx_SpecialS.c, src/melee/ft/chara/ftGameWatch/ftGw_Init.c, src/melee/ft/chara/ftKirby/ftKb_Init.c, src/melee/ft/chara/ftKoopa/ftKp_Init.c, src/melee/ft/chara/ftMasterHand/ftMh_Squeeze.c, src/melee/ft/chara/ftMewtwo/ftMt_SpecialS.c, src/melee/ft/chara/ftNana/ftNn_Init.c, src/melee/ft/chara/ftNess/ftNs_AttackHi4.c, src/melee/ft/chara/ftNess/ftNs_AttackLw4.c, src/melee/ft/chara/ftPopo/ftPp_Init.c, src/melee/ft/chara/ftPurin/ftPr_Init.c, src/melee/ft/chara/ftSeak/ftSk_SpecialS.c, src/melee/ft/fighter.c, src/melee/ft/ft_0877.h, src/melee/ft/types.h, tools/report_score.py
=> Partially match all of `ftCa_SpecialHi`

src/melee/ft/chara/ftPeach/ftPe_SpecialLw.c, src/melee/ft/chara/ftPeach/types.h
=> Match more of of `ftPe_SpecialLw`

src/melee/ft/chara/ftCommon/ftCo_CargoThrow.c
-|-|-|-
**File**|`0`|`42500`|`100.00%`
`ftCo_8009BF3C`|`0`|`6000`|`100.00%`
`ftCo_8009C02C`|`0`|`4800`|`100.00%`
`ftCo_8009C170`|`0`|`3900`|`100.00%`
`ftCo_8009C45C`|`0`|`3900`|`100.00%`
`ftCo_CargoWait2_Anim`|`0`|`2500`|`100.00%`
`ftCo_CargoWait2_Coll`|`0`|`2500`|`100.00%`
`ftCo_CargoThrowAir_Anim`|`0`|`1700`|`100.00%`
`ftCo_CargoThrowF_Anim`|`0`|`1700`|`100.00%`
`ftCo_CargoThrowAir_Coll`|`0`|`1000`|`100.00%`
`ftCo_CargoThrowB_Coll`|`0`|`1000`|`100.00%`
`ftCo_CargoThrowF_Coll`|`0`|`1000`|`100.00%`
`ftCo_CargoThrowHi_Coll`|`0`|`1000`|`100.00%`
`ftCo_CargoThrowLw_Coll`|`0`|`1000`|`100.00%`
`ftCo_CargoThrowAir_Phys`|`0`|`800`|`100.00%`
`ftCo_CargoThrowB_Anim`|`0`|`800`|`100.00%`
`ftCo_CargoThrowB_IASA`|`0`|`800`|`100.00%`
`ftCo_CargoThrowB_Phys`|`0`|`800`|`100.00%` …
=> Match `ftCo_8009BF3C`

.github/README.md, .github/packages/build-linux/Dockerfile, .github/packages/build-windows/Dockerfile
Need to merge this before https://github.com/doldecomp/melee/pull/958 to update docker images
=> Update compiler zip urls

Makefile, src/melee/gm/gmmain_lib.c, src/melee/it/it_26B1.c, src/melee/it/it_26B1.h, src/sysdolphin/baselib/lobj.c
=>  Remove frank, build with 1.2.5n

src/melee/ft/chara/ftPurin/ftPr_Init.c, src/melee/ft/chara/ftPurin/ftPr_Init.h, src/melee/ft/chara/ftPurin/types.h
Match some of the functions that were inline asm.
=> ftPurin matches

src/melee/ft/chara/ftPeach/ftPe_Float.c, src/melee/ft/chara/ftPeach/ftPe_Float.h, src/melee/ft/chara/ftPeach/ftPe_FloatAttack.c, src/melee/ft/chara/ftPeach/ftPe_FloatFall.c, src/melee/ft/chara/ftPeach/ftPe_FloatFall.h, src/melee/ft/chara/ftPeach/ftPe_SpecialS.c
* Addressed some functions that were fixed by new compiler
* Fixed a few functions that needed work
=> ftPeach Matches

asm/melee/ft/ft_08A4.s, obj_files.mk, src/melee/ft/ft_0BEC.h, src/melee/ft/ft_0BEF.c, src/melee/ft/ft_0BEF.h, src/melee/ft/ftdemo.c
-|-|-|-|-
**File**|`96 bytes`|`0`|`2,400`|`100.00%`
`ftCo_800BEFD4`|`96 bytes`|`0`|`2,400`|`100.00%`
=> Match `ft_0BEF`

src/sysdolphin/baselib/pobj.h
=> Fix comment in `pobj.h`

asm/melee/ft/ft_0C31.s, obj_files.mk, src/melee/ft/chara/ftCommon/ftCo_DemoCallback0.c, src/melee/ft/chara/ftCommon/ftCo_DemoCallback0.h, src/melee/ft/ft_0C31.h, src/melee/ft/ftdemo.c
-|-|-|-|-
**File**|`96 bytes`|`0`|`2,400`|`100.00%`
`ftCo_800C6150`|`96 bytes`|`0`|`2,400`|`100.00%`
=> Match `ftCo_DemoCallback0` (96 bytes)

.github/workflows/build-melee.yml, .github/workflows/dump-asm.yml, .github/workflows/publish-pages.yml
Otherwise when I'm pushing to my fork, the action tries to pull the image using my fork's owner/name which doesn't exist.
Drafting because if this is the correct solution, all the case/esac and tr stuff should be removed as well.
=> Hardcode image name

src/sysdolphin/baselib/gobj.c, src/sysdolphin/baselib/jobj.c, src/sysdolphin/baselib/shadow.c
Several functions were making obvious inline function calls, so I've corrected them to the proper inline.
=> Cleanup several functions to use inlines in HSD

src/melee/it/items/itluigifireball.c
-|-|-|-|-
**File**|`868 bytes`|`0`|`21,500`|`100.00%`
`it_802C0368`|`296 bytes`|`0`|`7,400`|`100.00%`
`it_802C01AC`|`208 bytes`|`0`|`5,200`|`100.00%`
`it_802C027C`|`104 bytes`|`0`|`2,600`|`100.00%`
`it_802C031C`|`76 bytes`|`0`|`1,900`|`100.00%`
`it_802C02E4`|`56 bytes`|`0`|`1,200`|`100.00%`
`it_802C0498`|`32 bytes`|`0`|`800`|`100.00%`
`it_802C04D0`|`32 bytes`|`0`|`800`|`100.00%`
`it_802C04F0`|`32 bytes`|`0`|`800`|`100.00%`
`it_802C0490`|`8 bytes`|`0`|`200`|`100.00%`
`it_802C04B8`|`8 bytes`|`0`|`200`|`100.00%`
`it_802C04C0`|`8 bytes`|`0`|`200`|`100.00%`
`it_802C04C8`|`8 bytes`|`0`|`200`|`100.00%`
=> Match `itluigifireball` (868 bytes)

tools/config-dtk/src/main.rs
=> Improve symbol handling in `config-dtk`

Cargo.lock, tools/config-dtk/Cargo.toml, tools/config-dtk/src/cw_map.rs, tools/config-dtk/src/dtk_config.rs, tools/config-dtk/src/main.rs
=> Parse `symbols.txt` in `config-dtk`

.github/workflows/publish-pages.yml
=> Disable `publish-pages`

src/melee/it/it_266F.c, src/melee/it/it_2725.h
=> Match `it_8026D9A0`

src/dolphin/gx/GXAttr.c, src/dolphin/gx/GXAttr.h, src/dolphin/gx/GXFrameBuf.c, src/dolphin/gx/GXFrameBuf.h, src/dolphin/gx/GXTexture.c, src/dolphin/gx/GXTexture.h, src/dolphin/mtx.h, src/sysdolphin/baselib/forward.h, src/sysdolphin/baselib/jobj.c, src/sysdolphin/baselib/jobj.h, src/sysdolphin/baselib/pobj.c, src/sysdolphin/baselib/shadow.c, src/sysdolphin/baselib/shadow.h, src/sysdolphin/baselib/texp.h
Matches most of shadow. The missing functions rely on some VEC code we didn't have prototypes setup for, and will likely get to them in the future.
=> Work on sysdolphin's shadow

src/dolphin/mtx.h, src/dolphin/mtx/vec.h, src/melee/lb/lbcollision.c, src/melee/lb/lbvector.c, src/sysdolphin/baselib/displayfunc.c, src/sysdolphin/baselib/displayfunc.h, src/sysdolphin/baselib/dobj.h, src/sysdolphin/baselib/jobj.h, src/sysdolphin/baselib/mtx.h, src/sysdolphin/baselib/tobj.c
Still lacking the following:
* mkBillboardMtx
* mkVBillboardMtx
* mkHBillboardMtx
These are nothing like the later version used in other games from what I can tell, so it's going to take referencing some of the generated stuff on `mkRBillBoardMtx` that I matched to try and work them out.
=> displayfunc matches

src/melee/ft/chara/ftSeak/ftSk_SpecialLw.c
=> Match `fn_8011412C` (52 bytes)

.github/workflows/publish-pages.yml
=> Fix `publish-pages`

configure.py, tools/project.py
=> Print trophies and event matches in Ninja build

.github/workflows/build.yml
Should fix this workflow on forks.
=> Move GitHub Pages setup step to deploy job

src/melee/mn/mndeflicker.c, src/melee/mn/mnhyaku.c, src/sysdolphin/baselib/gobj.h, src/sysdolphin/baselib/sislib.c, src/sysdolphin/baselib/sislib.h
Will improve names for structs and variables as I work on files in `mn`.
=> Match 34% of `sislib`

src/melee/ft/chara/ftCommon/ftCo_0A01.c, src/melee/ft/chara/ftCommon/ftCo_0A01.h, src/melee/ft/types.h, src/melee/it/it_266F.h, src/melee/it/it_26B1.c, src/melee/it/it_26B1.h, src/melee/it/types.h, src/melee/mp/mpisland.c, src/melee/mp/mpisland.h, src/melee/mp/types.h, tools/wiki_tu.py
-|-|-|-|-
**File**|`81.08 KB`|`1,688,212`|`1,979,800`|`14.73%`
`ftCo_800A1F3C`|`92 bytes`|`945`|`2,300`|`58.91%`
`ftCo_800A2718`|`440 bytes`|`3,350`|`11,000`|`69.55%`
`ftCo_800A49B4`|`140 bytes`|`740`|`3,500`|`78.86%`
`ftCo_800A80E4`|`300 bytes`|`1,581`|`7,500`|`78.92%`
`ftCo_800A1AB4`|`132 bytes`|`535`|`3,300`|`83.79%`
`ftCo_800B0760`|`440 bytes`|`1,750`|`11,000`|`84.09%`
`ftCo_800A0DA4`|`348 bytes`|`1,370`|`8,700`|`84.25%`
`ftCo_800AC30C`|`296 bytes`|`615`|`7,400`|`91.69%`
`ftCo_800B0E98`|`388 bytes`|`393`|`9,700`|`95.95%`
`ftCo_800A3710`|`308 bytes`|`215`|`7,700`|`97.21%`
`ftCo_800A0F00`|`176 bytes`|`110`|`4,400`|`97.50%`
`ftCo_800A4A40`|`428 bytes`|`205`|`10,700`|`98.08%`
`ftCo_800A0FB0`|`108 bytes`|`48`|`2,700`|`98.22%`
`ftCo_800B3900`|`92 …
=> Match 14.73% of `ftCo_0A01` (81.08 KB)

src/melee/ft/chara/ftCommon/ftCo_0A01.c, src/melee/ft/chara/ftCommon/ftCo_0A01.h, src/melee/ft/types.h, src/melee/gr/ground.c, src/melee/gr/stage.c, src/melee/gr/types.h
-|-|-|-|-
**File**|`81.08 KB`|`1,647,891`|`1,979,800`|`16.76%`
`ftCo_800AD42C`|`288 bytes`|`6,477`|`7,200`|`10.04%`
`ftCo_800AFC40`|`508 bytes`|`7,854`|`12,700`|`38.16%`
`ftCo_800A1F3C`|`92 bytes`|`845`|`2,300`|`63.26%`
`ftCo_800B0918`|`476 bytes`|`3,884`|`11,900`|`67.36%`
`ftCo_800A2718`|`440 bytes`|`3,350`|`11,000`|`69.55%`
`ftCo_800A50D4`|`448 bytes`|`2,854`|`11,200`|`74.52%`
`ftCo_800A49B4`|`140 bytes`|`740`|`3,500`|`78.86%`
`ftCo_800A80E4`|`300 bytes`|`1,436`|`7,500`|`80.85%`
`ftCo_800A1AB4`|`132 bytes`|`535`|`3,300`|`83.79%`
`ftCo_800B0760`|`440 bytes`|`1,750`|`11,000`|`84.09%`
`ftCo_800A0DA4`|`348 bytes`|`1,370`|`8,700`|`84.25%`
`ftCo_800A3554`|`444 bytes`|`1,195`|`11,100`|`89.23%`
`ftCo_800AC30C`|`296 bytes`|`615`|`7,400`|`91.69%`
`ftCo_800B0CA8`|`496 …
=> Match 16.76% of `ftCo_0A01` (81.08 KB)

src/sysdolphin/baselib/cobj.c, src/sysdolphin/baselib/cobj.h, src/sysdolphin/baselib/util.h, src/sysdolphin/baselib/wobj.h
* Matches essentially all functions left with stack/inlining issues that are not yet addressed
* Matches setupBottomHalfCamera
=> Work on CObj

configure.py, obj_files.mk
This was already matched and just hadn't been marked as matching.
=> Mark itcoin as matching

src/MSL/math.h, src/dolphin/pad/pad.h, src/melee/gm/gmmain.c, src/sysdolphin/baselib/controller.c, src/sysdolphin/baselib/controller.h, src/sysdolphin/baselib/util.h
2 remaining issues:
* HSD_PadRenewRawStatus has a copy that is being swapped around
* HSD_PadADConvertCheck1 has an issue with the stack
=> Nearly match sysdolphin/controller.c

src/melee/ft/chara/ftCommon/ftpickupitem.c
* Rearranged stack variables in 800942A0 to get it closer to a match
* Fixed up stack padding to use PAD_STACK which fixed sdata2
* Removed fake inlines
=> Cleanup Ftpickupitem

src/melee/ft/chara/ftCommon/ftCo_ItemThrow.c
* Removed some junk inlines
* Matched a couple functions
* Use PAD_STACK where applicable
=> ftCo_ItemThrow cleanup and matches

src/melee/gm/gm_1A36.static.h
Fixes broken matches from https://github.com/doldecomp/melee/pull/1535
=> Fix gm_1A36 bss ordering

src/melee/cm/camera.c
See [here](https://decomp.me/scratch/BBLZY) for the match.
=> feat: match `Camera_80030788`

src/melee/gr/grgarden.c, src/melee/gr/grkraid.c, src/melee/gr/grkraid.h, src/melee/gr/grvenom.c, src/melee/gr/gryorster.c, src/melee/gr/types.h, src/melee/if/if_2F72.h, src/melee/if/ifall.c, src/melee/if/ifall.h, src/melee/if/ifall.static.h, src/melee/if/ifstock.h, src/melee/if/iftime.h
* Match some small gr functions and a few larger ones
* Mach an ifAll function
=> Various matches

src/melee/gr/grbattle.c, src/melee/gr/types.h
* Use enum for background transition states
* Add Battle union member to Ground struct with named members
* Factor out helper function for timer
=> Clean up grbattle

configure.py, extern/dolphin/include/dolphin/os.h, extern/dolphin/src/dolphin/os/OSExi.c
This is a mixture of code from Pikmin 1, SMS, and a few tweaks by hand.
=> Match dolphin OSExi

src/melee/ft/chara/ftYoshi/ftYs_SpecialN.c, src/melee/ft/chara/ftYoshi/ftYs_SpecialN.h, src/melee/ft/chara/ftYoshi/types.h, src/melee/ft/ft_081B.c, src/melee/ft/ft_081B.h
Also modified some ftYoshi SpecialNVars and declarations in ft_081B for better matching
=> Some more ftYs_SpecialN matches

src/melee/it/items/itdrmariopill.c
=> Simplify it_802C0E48 control flow

src/melee/ft/chara/ftCommon/ftCo_0A01.c, src/melee/ft/types.h
Fix some small mismatches in functions that caused them to not be 100% matched
=> ftCo_0A01 fixups

src/melee/it/items/itdrmariopill.c, src/melee/it/items/itdrmariopill.h
=> itdrmariopill.c matches

src/melee/gr/forward.h, src/melee/gr/grcastle.c, src/melee/gr/grcastle.h
Two more tables down, and a few small functions.
=> grcastle work

src/melee/ft/fighter.c, src/melee/ft/ft_0877.c, src/melee/ft/ft_0877.h, src/melee/gr/grcastle.c, src/melee/pl/plbonuslib.c
Also clean up some ft_0877 return types
=> Use It_Kind values with itGetKind

src/melee/ft/chara/ftFox/ftFx_AppealS.c, src/melee/ft/chara/ftFox/ftFx_SpecialHi.c, src/melee/ft/chara/ftFox/ftFx_SpecialLw.c, src/melee/ft/chara/ftFox/ftFx_SpecialN.c, src/melee/ft/chara/ftFox/ftFx_SpecialS.c
Remove unnecessary:
* Casts
* Parentheses
* `U` unsigned literal suffix
* Comparisons to `false`
* Stack padding
=> Simplify ftFox code
