Makefile
Other name wasn't cutting it. Checking MSYS caught my terminal and set the WINDOWS flag as expected.
=> Add another possible shell uname for checking Windows

obj_files.mk, src/melee/gr/grtness.c, src/melee/gr/grtness.h
This code is line for line the same as GrTMars essentially, as well as some of the other Target Tests stages. So once the remaining C code is matched, it can be effectively copy-pasted around to match for like 8 stages.
=> Convert GrTNess to C and match basic functions

Makefile, asm/extabindex.s, asm/sdata.s, src/runtime/__init_cpp_exceptions.c
Switches to the 1.3.2 linker, since it's faster - while not as fast as 2.7 and not as finnicky to get changed to, and won't lead to my grandchildren being the ones that have to finish the decomp.
=> Switch to using the 1.3.2 linker

.gitignore, Makefile
prevents a really long string from being printed to console. this prevents errors if too many source files are in a repository.
=> futureproof makefile

src/melee/lb/lbvector.c
This PR corrects the comment about the sine/cosine functions. They're actually approximations derived through the Gran-Schmidt procedure, not the Taylor series.
=> Correct comment on sine/cosine approx functions

Makefile, src/sysdolphin/baselib/fobj.c, src/sysdolphin/baselib/gobjgxlink.c
This fixes the fake match in FObj from the weird unrolled loop.
Marks GObj_GXReorder as dont_inline since otherwise it gets inlined into GObj_SetupGXLink.
=> Enable inline_auto, fix FObj match, and mark GObj_GXReorder as dont_inline

Makefile
Before:
```
D:\code\game_decomps\melee>make
Frank is fixing src/melee/lb/lblanguage.c
Frank is fixing src/melee/lb/lbcommand.c
Frank is fixing src/melee/lb/lbvector.c
Frank is fixing src/melee/lb/lbtime.c
Frank is fixing src/melee/lb/lbfile.c
Frank is fixing src/melee/lb/lbarchive.c
Frank is fixing src/melee/ft/chara/ftpeach.c
Frank is fixing src/melee/gr/stage.c
Frank is fixing src/sysdolphin/baselib/tobj.c
Frank is fixing src/sysdolphin/baselib/aobj.c
Frank is fixing src/sysdolphin/baselib/fobj.c
Frank is fixing src/sysdolphin/baselib/robj.c
Frank is fixing src/sysdolphin/baselib/wobj.c
Frank is fixing src/sysdolphin/baselib/texp.c
Frank is fixing src/sysdolphin/baselib/list.c
Frank is fixing src/sysdolphin/baselib/archive.c
Frank is fixing src/sysdolphin/baselib/displayfunc.c
Frank is …
```
=> don't have to rerun frank on untouched files

src/melee/pl/player.c, src/melee/pl/player.h
found this needed to be fixed for other functions that call this to match, this fix doesn't break anything and still matches.  should not need review.
=> small fix to player.c

include/functions.h, src/melee/ft/fighter.h, src/sysdolphin/baselib/jobj.h
The decompilation pass in mips_to_c is a bit stricter than MWCC - this fixes the headers so they can be used as context without modification
=> Minor fixes for mips_to_c decompilation

asmdiff.sh
Some systems do not put the bash executable in /bin/bash;
`/usr/bin/env bash` is generally considered more portable
=> Use portable bash shebang for asmdiff

.github/workflows/build.yml, Makefile, tools/calcprogress.py
Builds the whole repo & runs calcprogress on every commit / pull request.
Successful build: https://github.com/encounter/melee/runs/5892809678
calcprogress.py was modified slightly to use the passed-in dol & map file instead of using hardcoded values.
Additionally, on *nix, DEVKITPPC is set to its default location (unless overridden) and Wine debug output is silenced.
=> ci: Add GitHub action

src/melee/ft/fighter.c, src/melee/ft/fighter.h
Update some members used by newly matched
Fighter_Unload_8006DABC to avoid some explicit casts
=> Refine fighter member pointer types

src/melee/ft/fighter.c, src/melee/ft/fighter.h
sizeof(ftHit) is 0x138
`0x1198 - 0x1064 - 0x138 == -4`
`x1064_thrownHitbox` should be from 0x1064 to 0x119C, but there's a filler and something at 0x1198.
```
ft->x1064_thrownHitbox.filler_x0[0] = sizeof(ftHit);
ft->filler_x1064[0] = sizeof(ft->filler_x1064);
ft->x1198 = 1;
```
compiles to:
```
+  145848:      38 00 00 38     li      r0,56
+  14584c:      38 60 00 fc     li      r3,252
+  145850:      98 04 10 64     stb     r0,4196(r4)
+  145854:      38 00 00 01     li      r0,1
+  145858:      98 64 11 9c     stb     r3,4508(r4)
+  14585c:      90 04 11 98     stw     r0,4504(r4)
```
which is to say:
```
ft->x1064 = 0x38
ft->x119C = 0xFC
ft->x1198 = 1
```
the first size being 0x38 instead of 0x138 is because its truncated to u8
0xFC is the same as -4
and the last write is to an element …
=> Remove negative sized padding

Makefile
Now you can `make MAX_ERRORS=1` to just see one error at a time and not get your console flooded.
=> add new Makefile setting to limit number of errors printed per file

.gitignore
Ignores user data from PyCharm, CLion, Rider, etc. Appended from [JetBrains.gitignore](https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore).
=> Ignore JetBrains metadata

.vscode/settings.json
Requires the "[Replace Rules](https://marketplace.visualstudio.com/items?itemName=bhughes339.replacerules)" extension for VS Code.
The primary usage is to highlight a block of asm functions, use the `replacerules.runRuleset` command, and select "Embed asm in C" to convert them to inline asm.
=> Add `replacerules` snippets

Makefile, build.sh
In `Makefile` and `build.sh`. The check is still enabled by default.
=> Support skipping the `SHA1` check

include/common_structs.h, src/melee/ft/chara/ftNess/ftNess_AttackHi4.c, src/melee/ft/chara/ftNess/ftNess_SpecialLw.c, src/melee/ft/chara/ftNess/ftNess_SpecialS.c, src/melee/ft/fighter.h, src/melee/ft/ftcoll.c, src/melee/it/item.c, src/melee/it/item.h
=> Standardize ground/air constants to `GroundOrAir` enum

include/sysdolphin/baselib/jobj.h, src/melee/ft/fighter.c
This affects at least two functions, also affects HSD_JObjSetFlagsAll since the manual inlining was required to fix the function. The solution may be that this function is a defined macro instead of an inline, which is rather odd, but it's the only thing that fixes both hacks/functions.
=> Fix SetScaleHack by making HSD_JObjSetMtxDirty a macro.

tools/calcprogress/calcprogress.py
Matches the output of old `calcprogress`.
=> Remove extraneous newline from `calcprogress` output

tools/frank.py
Fixes Player_80032BB0 in src/melee/pl/player.c
Unfortunately, we cannot remove the player.c kludge from our Makefile, because Player_GetPtrForSlot is still broken by frank.
=> frank.py: Also swap fdivs instruction

include/sysdolphin/baselib/texp.h, src/sysdolphin/baselib/mobj.c
Cleanup  across the MObj file that was recently merged, since MakeTExp with the constants included is almost necessary to understand what the TExp functions are doing later.
=> Cleanup MObjMakeTExp with TExp constants, variable naming and simplification, and assert lines from hex to decimal

.gitignore, build.sh
Dumps the dol back to `/dump` when the build is completed, if `-d` is passed. Requires `dadosod`, which you can install using:
```sh
cargo install --git https://github.com/InusualZ/dadosod
```
If you don't have `cargo`, you need to [install Rust](https://www.rust-lang.org/tools/install).
The `dump` folder is also synchronized to `expected`, when `-e` is passed.
=> Implement dump (`-d`) flag in `build.sh`

include/dolphin/dsp/dsp.h, include/dolphin/os/OSContext.h, include/dolphin/os/OSThread.h, include/dolphin/types.h, src/dolphin/card/CARDFormat.c, src/dolphin/card/CARDMount.c, src/dolphin/dvd/dvd.c, src/dolphin/gx/__types.h, src/dolphin/os/OS.c, src/dolphin/os/OSInterrupt.c, src/dolphin/os/OSMemory.c, src/dolphin/os/OSReset.c, src/dolphin/os/OSResetSW.c, src/dolphin/os/OSSerial.c, src/dolphin/os/OSTime.c
This macro expands to an appropriate expression depending on the compiler, so these fixed-address declarations can still be used with decomp-permuter and non-MWCC compilers.
=> Use AT_ADDRESS macro for fixed-address declarations

Doxyfile, include/functions.h, include/variables.h
Temporary measure to make removing `functions.h` and `variables.h` easier. Can be viewed at the [Modules](https://ribbanya.github.io/melee/modules.html) page.
=> Divide `functions.h` into Doxygen modules

asm/melee/ft/ftanim.s, include/sysdolphin/baselib/jobj.h, src/melee/ft/ftparts.c
The diff got messed up because master didn't have make format run after the .clang-format changes.
=> Some ftparts.c decomp and various cleanup + naming

include/common_structs.h, src/melee/gr/grdynamicattr.c
This typedef does nothing, and causes issues for m2c.
=> Remove redundant typedef

src/dolphin/dsp/dsp.c, src/dolphin/dsp/dsp.h
reasonably certain this is what it is based on Pikmin 1's map, which has the same functions, albeit UNUSED
=> rename unknown dsp func from pik1 map

.github/workflows/editorconfig.yml
Apparently I can't reopen #747. Anyway:
* Use fixed Ubuntu version
* Remove hardcoded references to `doldecomp`
* Now works on PRs to any repo
* Update `grep` exclude filter
* Run `editorconfig-checker` in verbose mode
* Add markdown step summary
Successful [run](https://github.com/ribbanya/melee/actions/runs/4299967378).
=> Improve editorconfig workflow QoL

.github/workflows/build.yml, Makefile
1. Add Windows build
* This build relies only on PowerShell, MinGW, Git for Windows, and Python 3; no more MSYS2 or devkitPro.
* It mirrors the actions of the Ubuntu build except for uploading the map artifact.
2. Use a new compilers zip
* Only contains binaries we actually use, including a pre-patched 1.1 linker, as well as `powerpc-eabi-as.exe` which is needed for the Windows build.
3. Improve speed of Ubuntu build
* Download the `wibo` binary from their CI release instead of building it ourselves.
* The sha1 of the 0.4.1 binary is hard-coded and was double-checked locally by me.
* This lets us cut down on the packages installed.
4. Clean up the build script
* Use version numbers everywhere instead of `latest` to avoid future breakages.
* Prefer breaking up long lines for readability …
=> Add Windows build job and improve speed of Ubuntu build

.github/README.md
* Windows
* Tested on a fresh Windows 10 Home installation. You can just copy-paste the instructions into PowerShell and it works.
* Linux
* Cleaned up the instructions a bit, updated the compilers zip.
* Containers
* Added a section about running from a Docker image, tested locally.
=> Improve README instructions

tools/ctx_template.html
I was following along with the [getting started instructions](https://doldecomp.github.io/melee/getting_started.html#:~:text=Copy%20in%20the%20contents%20of%20this%20link%20into%20the%20%E2%80%9CContext%E2%80%9D%20section.%20More%20on%20that%20later.) and I noticed the [copy button](https://doldecomp.github.io/melee/ctx.html) for the target assembly wasn't working for me.
At first I thought the button was broken, but after looking into it some more I found out that it was because I did not have the text expanded. `innerText` returns an empty string when the text in collapsed because it is trying to emulate what the the user would be able to copy if they were to highlight the content with their mouse.
Using `.textContent` to get the text will always return the correct content to be copied.
=> Use `.textContent` to get text from the `#ctx-text` element

Makefile, tools/objdiff-make.sh
Set "Custom make program" in `objdiff` to point to `tools/objdiff-make.sh`. Requires `wibo` on your path. If you're on Windows, alias `wibo` it to a no-op or something idk.
=> Tweak `Makefile` to be more convenient with `objdiff`

asm/melee/ft/ft_08A4.s, obj_files.mk, src/melee/ft/chara/ftCommon/ftCo_ShieldBreakDown.c, src/melee/ft/chara/ftCommon/ftCo_ShieldBreakDown.h, src/melee/ft/chara/ftCommon/ftCo_ShieldBreakStand.c, src/melee/ft/chara/ftCommon/ftCo_ShieldBreakStand.h, src/melee/ft/ft_08A4.h
-|-|-|-
**File**|`0`|`6400`|`100.00%`
`ftCo_80098E3C`|`0`|`3200`|`100.00%`
`ftCo_ShieldBreakDown_Anim`|`0`|`1500`|`100.00%`
`ftCo_ShieldBreakDown_Coll`|`0`|`800`|`100.00%`
`ftCo_ShieldBreakDown_Phys`|`0`|`800`|`100.00%`
`ftCo_ShieldBreakDown_IASA`|`0`|`100`|`100.00%`
=> Match `ftCo_ShieldBreakDown`

src/melee/ft/chara/ftCommon/ftCo_ShieldBreakStand.c, src/melee/ft/ft_08A4.h
-|-|-|-
**File**|`0`|`5300`|`100.00%`
`ftCo_80098F3C`|`0`|`2100`|`100.00%`
`ftCo_ShieldBreakStand_Anim`|`0`|`1500`|`100.00%`
`ftCo_ShieldBreakStand_Coll`|`0`|`800`|`100.00%`
`ftCo_ShieldBreakStand_Phys`|`0`|`800`|`100.00%`
`ftCo_ShieldBreakStand_IASA`|`0`|`100`|`100.00%`
=> Match `ftCo_ShieldBreakStand`

asm/melee/ft/ft_08A4.s, src/melee/ft/chara/ftCommon/ftCo_Escape.c
-|-|-|-
**File**|`0`|`56700`|`100.00%`
`ftCo_EscapeN_Anim`|`0`|`1500`|`100.00%`
`ftCo_EscapeN_Coll`|`0`|`800`|`100.00%`
`ftCo_EscapeN_Phys`|`0`|`800`|`100.00%`
`ftCo_EscapeN_IASA`|`0`|`100`|`100.00%`
=> Match `ftCo_EscapeN`

asm/melee/ft/ft_08A4.s, obj_files.mk, src/melee/ft/chara/ftCommon/ftCo_CliffAttack.c, src/melee/ft/chara/ftCommon/ftCo_CliffClimb.c, src/melee/ft/chara/ftCommon/ftCo_CliffEscape.c, src/melee/ft/chara/ftCommon/ftCo_CliffEscape.h, src/melee/ft/chara/ftCommon/ftCo_Init.c, src/melee/ft/ft_0877.h, src/melee/ft/ft_08A4.h
-|-|-|-
**File**|`0`|`7600`|`100.00%`
`ftCo_8009B040`|`0`|`5100`|`100.00%`
`ftCo_CliffEscape_Anim`|`0`|`800`|`100.00%`
`ftCo_CliffEscape_Coll`|`0`|`800`|`100.00%`
`ftCo_CliffEscape_Phys`|`0`|`800`|`100.00%`
`ftCo_CliffEscape_IASA`|`0`|`100`|`100.00%`
=> Match `ftCo_CliffEscape`

src/common_structs.h, src/melee/ft/chara/ftCLink/ftCl_Init.c, src/melee/ft/chara/ftCommon/ftCo_DamageIce.h, src/melee/ft/chara/ftCommon/ftCo_Guard.c, src/melee/ft/chara/ftLink/ftLk_AttackAir.c, src/melee/ft/chara/ftMars/ftMs_SpecialLw.c, src/melee/ft/chara/ftPeach/ftPe_SpecialN.c, src/melee/ft/ftcoll.c, src/melee/ft/ftcoll.h
Resolves part of #595.
-|-|-|-|-
**File**|`23.89 KB`|`540,965`|`594,400`|`8.99%`
`ftColl_CreateReflectHit`|`136 bytes`|`0`|`3,400`|`100.00%`
`ftColl_8007B1B8`|`132 bytes`|`0`|`3,300`|`100.00%`
`ftColl_CreateAbsorbHit`|`92 bytes`|`0`|`2,300`|`100.00%`
=> Partially match `ftcoll`

src/melee/ft/ftcoll.c, src/melee/lb/lbcollision.h
Resolves part of #595.
-|-|-|-|-
**File**|`23.89 KB`|`510,471`|`594,400`|`14.12%`
`ftColl_80078C70`|`1.52 KB`|`7,406`|`37,900`|`80.46%`
=> Partially match `ftColl_80078C70`

src/melee/ft/chara/ftPurin/ftPr_Init.c, src/melee/ft/fighter.c, src/melee/lb/lbcollision.c, src/sysdolphin/baselib/jobj.h
HSD_JObjSetupMatrix failed to inline into lbcoll,
so trying to match that copy shows us that the definition must be modified.
HSD_JObjGetMtx is actually HSD_JObjGetMtxPtr, which improves some matches in melee/ft.
=> Impove jobj inlines

src/melee/it/forward.h, src/melee/it/it_266F.h, src/melee/it/it_26B1.c, src/melee/it/it_26B1.h, src/melee/it/item.c, src/melee/it/types.h, src/melee/lb/lbcollision.h
A number of functions in itcoll pass `&Item->x5D4` to functions which expect a HitCapsule, and known areas of itHit/HitCapsule are identical, so we can merge the structs.
=> Remove itHit struct

tools/frank.py
frank's rescheduling passes were running through the entire object file,
potentially mucking up non-code regions. These should be restricted to
the .text section so that only functions are rescheduled.
The two commits following that are some cleanups to hopefully make the code a bit more readable.
=> frank.py: Restrict rescheduling to .text section

src/melee/lb/lbfile.c
Requires a dont_inline pragma as it'll inline the function into all the calls within the file.
=> Remove MUST_MATCH from lbfile due to new compiler

asm/sysdolphin/baselib/psappsrt.s, src/sysdolphin/baselib/psappsrt.c, src/sysdolphin/baselib/psappsrt.h, src/sysdolphin/baselib/psstructs.h
* Matches psInitAppSRT
* Removes erroneous `unk_t` typedef for an already defined struct
* Adds the `_generator` struct used in later psAppSRT code
=> Match psInitAppSRT, add/fix up psstructs

src/sysdolphin/baselib/object.h
Breaks context parsing on decomp.me without it.
=> Fix iref_INC to have a void type

.github/README.md, .github/packages/build-linux/Dockerfile, .github/packages/build-linux/setup.sh, .github/packages/build-windows/Dockerfile, .github/packages/build-windows/setup.ps1
Because hosting on Discord is [no longer an option](https://news.ycombinator.com/item?id=37697030).
=> Host `MELEE_COMPILERS_N.zip` on MEGA instead of Discord

src/melee/ft/ft_0BEC.c
Used some of the existing matched functions as a basis, fixed them up in cases where they didn't fully match.
There's a bit of a fakematch here as I think "setupInitialState" needs to have the `Fighter_ChangeMotionState` but having a Fighter pointer there seems to cause an `addi` instruction in `ftC0_800BED88` which strangely does not appear in decomp.me - so all in all a very weird file in terms of matching an obvious inline to fix the stack.
When testing, it seemed like there may be something differing between the implicit cast and accessing through GET_FIGHTER, so possibly something there but I'm just going to let the "fakematches" slide here.
=> ft_0BEC match cleanup

compile_flags.txt, src/Runtime/platform.h, src/dolphin/dvd/dvd.c, src/dolphin/dvd/dvd.h, src/dolphin/dvd/dvdlow.c, src/dolphin/dvd/dvdlow.h, src/dolphin/os/OSInit.h, src/dolphin/os/OSInterrupt.c, src/dolphin/os/OSResetSW.c, src/placeholder.h
-|-|-|-|-
**File**|`3.67 KB`|`2,655`|`91,700`|`97.10%`
`__DVDInterruptHandler`|`756 bytes`|`1,699`|`18,900`|`91.01%`
`DVDLowRead`|`664 bytes`|`951`|`16,600`|`94.27%`
`Read`|`272 bytes`|`5`|`6,800`|`99.93%`
`DVDLowReset`|`188 bytes`|`0`|`4,700`|`100.00%`
`DVDLowReadDiskID`|`164 bytes`|`0`|`4,100`|`100.00%`
`DVDLowAudioBufferConfig`|`156 bytes`|`0`|`3,900`|`100.00%`
`DVDLowInquiry`|`156 bytes`|`0`|`3,900`|`100.00%`
`DVDLowAudioStream`|`152 bytes`|`0`|`3,800`|`100.00%`
`DVDLowSeek`|`148 bytes`|`0`|`3,700`|`100.00%`
`DVDLowRequestAudioStatus`|`140 bytes`|`0`|`3,500`|`100.00%`
`DVDLowRequestError`|`140 bytes`|`0`|`3,500`|`100.00%`
`DVDLowStopMotor`|`140 bytes`|`0`|`3,500`|`100.00%`
`AlarmHandler`|`132 bytes`|`0`|`3,300`|`100.00%`
`SeekTwiceBeforeRead`|`128 …
=> Match 97.10% of `dvdlow` (3.67 KB)

src/dolphin/dvd/dvderror.c
-|-|-|-|-
**File**|`344 bytes`|`1,052`|`8,600`|`87.77%`
`__DVDStoreErrorCode`|`344 bytes`|`1,052`|`8,600`|`87.77%`
=> Match 87.77% of `dvderror` (344 bytes)

tools/revert_asm.py
```
usage: revert_asm.py [-h] C_FILE
revert a C file to asm for make
positional arguments:
C_FILE      the source file to revert
options:
-h, --help  show this help message and exit
```
=> Create `revert_asm.py` to unlink C files from `make`

tools/decomp.py, tools/m2ctx/m2ctx.py
> If you’re on a recent version of Windows 10 or better, and your stdout/stderr are pointing to a Windows console, then this will flip the magic configuration switch to enable Windows’ built-in ANSI support.
> 
> If you’re on an older version of Windows, and your stdout/stderr are pointing to a Windows console, then this will wrap sys.stdout and/or sys.stderr in a magic file object that intercepts ANSI escape sequences and issues the appropriate Win32 calls to emulate them.
> 
> In all other circumstances, it does nothing whatsoever. Basically the idea is that this makes Windows act like Unix with respect to ANSI escape handling.
https://pypi.org/project/colorama/
=> Fix colored output of tools on Windows

src/sysdolphin/baselib/tev.c
These were set as integer arrays, which would make matching HSD_SetupChannel impossible.
I've fixed this, so that if someone gets to it before I do - they have less work.
=> Fix prev_ch and invalid_prev_ch types in tev

configure.py, src/sysdolphin/baselib/lobj.c, src/sysdolphin/baselib/lobj.h
The index is uninitialized in the case of an invalid GXLightID - because it's going to assert.
The attempt to fix this was making the file non-matching.
=> Fix LObj match being broken by someone's bugfix

.github/README.md
Waiting on #1085 and #1102. `publish-packages` has a similar problem to #1102, but the whole thing probably needs to be rewritten.
=> Remove failing CI badges for now

src/melee/it/items/itegg.c, src/melee/it/items/itentei.c, src/melee/it/items/itmetalb.c, src/melee/it/items/itpippi.c, src/melee/it/items/itraikou.c, src/melee/it/items/itsuikun.c, src/melee/it/items/itzrshell.c
Removes casts resulting from me copy-pasting from decomp.me, since it's been complaining about forward declarations.
=> Remove explicit casts in some item code

src/melee/ft/ft_0852.c
-|-|-|-|-
**File**|`836 bytes`|`16,800`|`20,500`|`18.05%`
`ft_8008521C`|`148 bytes`|`0`|`3,700`|`100.00%`
=> Match `ft_8008521C` (148 bytes)

src/melee/mn/forward.h, src/melee/mn/mncharsel.c, src/melee/mn/types.h
NOTE: This is my first time contributing to the decomp. So please don't hesitate to let me know if I've done anything "out of protocol" :)
mnCharSel_803F0A48 is primarily concerned with icon and mode data while mnCharSel_803F0DFC is concerned with the doors at the bottom of the screen.
Both appear to be pieces of data heavily used by other functions in mncharsel, so matching this should accelerate the decompilation of the CSS.
These data structures are also well known and propagated among various mods, Gecko codes, tools, etc.
I created two data structs for each of the memory structures with as much info as I could find then filled in the defaults into a variable in .data (where objdiff says they're located).
1. Objdiff shows 100% match for each and proper sizing
2. Through the use of …
=> Match mnCharSel_803F0A48 and mnCharSel_803F0DFC

tools/m2ctx/m2ctx.py
Don't print the entire context file on an error if `--quiet` is specified, making it easier to actually see the error message
=> m2ctx: Pass `--quiet` to error output

src/melee/ft/ftdynamics.c
Correct assert that was causing a lower match on a function
=> Correct assert in ftdynamics

src/melee/mp/forward.h, src/melee/mp/mplib.c, src/melee/mp/mplib.h, src/melee/mp/types.h
This is my first PR, sorry if I'm making obvious mistakes. Happy to engage on discord if that's easier.
100% matches on...
```
- mpLib_800588D0
- mpLib_80058970
- mpLib_800589D0
- mpLib_80058AA0
- mpLib_8005A2DC
```
Also got .sdata matching.
=> Decompile a handful of functions in mplib.c

configure.py
singlequotes don't work on windows
=> fix windows build

config/GALE01/splits.txt, configure.py
Had previously been matched and was not part of the file.
=> Fix to have __start match included in configure.py

config/GALE01/splits.txt, src/Runtime/__init_cpp_exceptions.c, src/Runtime/__init_cpp_exceptions.h, src/Runtime/global_destructor_chain.c, src/Runtime/platform.h
Code/data not specified in splits.txt will be auto-generated by dtk. Some of these autogenerated objects were easily matchable, another was a missing sda2 segment. The only remaining auto-split is MetroTRK exception.s (which is written in assembly anyway, so we can probably ignore it).
=> Cut down on auto splits

configure.py
They were only used by extern/dolphin/ and caused build failures when using --debug to get line number info in objdiff.
=> Remove DEBUG/NDEBUG flags from build script

tools/split_suggester.py
Now parses config/GALE01/symbols.txt and can handle dtk-generated asm files.
Usage: `python .\tools\split_suggester.py -s .\build\GALE01\asm\melee\ft\chara\ftKirby\ftKb_Init.s`
=> Fix split suggester
